[global]
   workgroup = WORKGROUP
   server string = LibraryIT Server
   security = user
   map to guest = never
   log file = /logs/libraryit.log
   max log size = 1000
   logging = file
   log level = 1

   vfs objects = full_audit

   full_audit:prefix = [%T] [%I] [%u]
   full_audit:success = connect disconnect mkdir rmdir open write rename unlink
   full_audit:failure = connect open write unlink rename
   full_audit:facility = LOCAL7
   full_audit:priority = NOTICE

[ebooks]
   path = /libraryit/ebooks
   browseable = yes
   read only = no

   valid users = @staff @readonly
   write list = @staff

[papers]
   path = /libraryit/papers
   browseable = yes
   read only = no

   valid users = @staff @readonly
   write list = @staff

[sourcecode]
   path = /libraryit/sourcecode
   browseable = no
   read only = no

   valid users = @staff
   write list = @staff

[docs]
   path = /libraryit/docs
   browseable = yes
   read only = yes

   valid users = @staff @readonly
   write list = librarian